name: 01-dispatch
on:
    workflow_dispatch:
jobs:
    dispatch-01:
        runs-on: ubuntu-latest
        steps:
            - name: Que pasa co hermanillo
              run: echo "Hola hermanillo"


