name: 06-secrets
on:
    workflow_dispatch:
    push:
jobs:
    aws-claves:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar claves
              run: |
                echo ${{ secrets.AWS_ACCESS_KEY_ID }}
                echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                echo ${{ secrets.AWS_REGION }}
                echo ${{ secrets.AWS_SESSION_TOKEN }}